### ISSUE TITLE
maybe i find a bug

### ISSUE THREAD

**Issue by htfhxx** [zlinao/Variational-Transformer#1]
when adding the data in data/persona/*_self_original.txt，the context is not fit to the responce. 

There are many utterences on each line. This code connects the first few dialogues on line n with the first few dialogues on line n + 1, but the former is not the context of the latter, ignoring so many information(or context) on line n.

**Comment by zlinao** [comment]
This is related to the original Persona dataset, where each user response (r) has also 10 possible candidate answers. The dataset file was structured as follow:
id \t user-turn \t response \t candidate1 | candidate2 | .... | candidate10

Check the link for more details
https://github.com/HLTCHKUST/PAML/issues/2#issuecomment-514393005

**Comment by htfhxx** [comment]
> This is related to the original Persona dataset, where each user response (r) has also 10 possible candidate answers. The dataset file was structured as follow:
> id \t user-turn \t response \t candidate1 | candidate2 | .... | candidate10
> 
> Check the link for more details
> [HLTCHKUST/PAML#2 (comment)](https://github.com/HLTCHKUST/PAML/issues/2#issuecomment-514393005)

get，3q~
